### ISSUE TITLE
5.7.3's 'Remake JS' errors out

### ISSUE THREAD

**Issue by EternityEngine** [Jonius7/SteamUI-OldGlory#27]
When I run the JS Tweaks portion of the program ('Remake JS' button in Settings/About), it errors out at the very end and doesn't apply, making Steam show nothing but a black screen in the viewing area. This happens even after I reset all changes. The 5.7.2 and 5.7.1.1 releases don't have this problem.

Here's the log output:

```
Running js_tweaker
Copying file library.js from Steam\steamui...
Copying file libraryroot.js from Steam\steamui...
library.js changing to use tweaked JS. (librery.js)
index.html changing to use tweaked JS.
index.html backup created at c:\program files (x86)\steam\steamui/index.html.original
Opening JS file and beautifying...
Writing beautified file... please do not close
Beautified file write finished
Finding Fixes...

FIX: t = this.props.rgInfo.slice(0, 12).map((function(t) {
FIX: return e = !1 !== this.props.collapsible ? this.props.expand ? "0px" : this.state.gameInfoHeight + "px" : "", r.createElement("div", {
FIX: className: ""
FIX: var t = this.props.details.vecScreenShots.slice(0, 9).map((function(t) {
FIX: hoverDelay: 300, style: this.props.app.installed ? {} : {opacity: "var(--UninstalledGameImageOpacity)"},
FIX: gridColumnGap: 5,
FIX: gridRowGap: 8,
FIX: gridColumnGap: 5,
FIX: gridRowGap: 8,
FIX: case 13: return this.RunApp(g.a.currentGameListSelection.nAppId), void e.preventDefault();case 38:
FIX: }, t.prototype.RunApp = function(e) {window.location.href = "steam://rungameid/" + e;}, t.prototype.MoveRangeSelectUpOneRow = function() {
FIX: gridColumnGap: 5,
FIX: gridRowGap: 8,
FIX: }(e), this.SetStateLoaded(),document.getElementsByClassName('smartscrollcontainer_Body_3lDcz')[0].scrollTop = 30, [3, 5];

Re-minify JS file

JS Minify complete. (libraryreet.js)
Files not found!
Run the other functions in js_tweaker first.
~~~~~~~~~~
Traceback (most recent call last):
  File "js_tweaker.py", line 258, in copy_files_to_steam
  File "shutil.py", line 435, in copy2
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'librery.js'
None
~~~~~~~~~~
```

**Comment by Rex117** [comment]
Hello guys, just wanted to put in my ¢2 on the matter. With the release of SteamUI-OldGlory-Release_5.7.4 this issue seems to be fixed, but you can still get a black screen if the "CLASSIC Sticky image background and spillover into sidebar (beta)" option is selected in the JS Options menu. Not selecting this option in Release_5.7.3 still produces the black screen. Through trial and error I was able to single out the source of the black screen in Release_5.7.4 to this. Here are screenshots of my settings and results on Steam Library
![Home](https://user-images.githubusercontent.com/52544680/137591123-20d69ff1-6c59-415c-85ac-53862fe1d15d.JPG)
![CSS Options](https://user-images.githubusercontent.com/52544680/137591129-8e366d17-5bba-4b24-b07e-c8515128594a.JPG)
:
![JS Options](https://user-images.githubusercontent.com/52544680/137591133-f3f859da-4873-4da1-96a8-cbf06b79e288.JPG)
![Library](https://user-images.githubusercontent.com/52544680/137591140-fbd41fbb-95d6-49cb-a348-cbd411ea70b6.JPG)

**Comment by Jonius7** [comment]
I've had a look, and the `CLASSIC Sticky image background and spillover into sidebar (beta)` option should be fixed now. 
7b69260d289713e86cde2829f140ec702c191c58

With this option, if you right click change a custom background, or remove it, it doesn't refresh right away, you usually need to click away to another game and back to it, to left it refresh/recache the new image. Not sure how I'd fix that, but otherwise it works.

**Comment by EternityEngine** [comment]
Hi, just wanted to confirm that 5.7.4 does fix this issue after a bit of fiddling. I'm not sure what the exact problem was, but at first it was still throwing the error, even after doing a reset. I cleaned out the steamui folder a bit (stuff from previous releases, etc.) and ran the app as administrator, and that seems to have done the trick.
